package com.glowseed.noctdock.receiver

internal fun formatReceiverDiagnostics(state: ReceiverUiState): String = buildString {
    appendLine("NoctDock receiver diagnostics")
    appendLine("Advertised name: ${state.advertisedName.ifBlank { state.defaultReceiverName }}")
    appendLine("Local IP: ${state.localIpAddress}")
    appendLine("Discovery port: ${state.port}")
    appendLine("Pairing state: ${state.pairingState}")
    appendLine("Pairing code visible: ${state.pairingCode.isNotBlank()}")
    appendLine("Advertising: ${state.advertising}")
    appendLine("UDP listening: ${state.udpListening}")
    appendLine("Trusted senders: ${state.trustedSenderCount}")
    appendLine("Handheld name: ${state.senderName.ifBlank { "None" }}")
    appendLine("Stream active: ${state.streamActive}")
    appendLine("Stream error: ${state.streamError ?: "None"}")
    appendLine("Status: ${state.status}")
    appendLine("Form factor: ${state.formFactor}")
    appendLine("Discovery lifecycle: ${state.discoveryLifecycleState}")
    appendLine("Broadcast restart attempts: ${state.broadcastRestartAttempts}")
    appendLine("Decoder: ${state.decoderName}")
    appendLine("Source app: ${state.sourceMetadata.sourceAppName.ifBlank { "Unknown" }}")
    appendLine("Incoming fps: ${state.metrics.receivedFps}")
    appendLine("Render fps: ${state.metrics.fps}")
    appendLine("Codec MIME: ${state.metrics.codecMime.ifBlank { "Unknown" }}")
    appendLine("Receiver decoder MIME: ${state.metrics.receiverDecoderMime.ifBlank { "Unknown" }}")
    appendLine("Reassembly drops: ${state.metrics.reassemblyDrops}")
    appendLine("Audio underruns: ${state.metrics.audioUnderruns}")
    appendLine("Audio drops: ${state.metrics.audioDrops}")
    appendLine("A/V offset ms: ${state.metrics.avOffsetMs}")
}
